name: Keep Render Webapp Alive

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Three Pings
        run: |
          for i in {1..3}; do
            echo "Ping attempt $i of 3 at $(date)"
            curl -X GET https://darija-back.onrender.com || echo "Ping failed"
            
            if [ $i -lt 3 ]; then
              echo "Waiting 5 minutes before next ping..."
              sleep 300
            fi
          done
        shell: bash
